### PR TITLE
Adding Crazeface's acceptance tests

### PR DESCRIPTION
**Pull request by crazeface**

### CODE REVIEW

**Comment by sam-yang** [comment]
Please limit your tests to between 50 and 100 lines according to the rubric.

**Comment by crazeface** [comment]
Fixed. Sorry about that

**Comment by sam-yang** [comment]
I think you have one extra line in your RunCollatz.in file; it won't make a difference in actual testing, but can you fix it just for consistency's sake?

**Comment by crazeface** [comment]
I think I got it now

**Comment by sam-yang** [comment]
Perfect, thanks.

**Pull request merged**
